version: "3"
services: 
  nginx:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=myverysecretcommonpassword
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

#  redis:
#    environment:




#docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
#docker compose -f docker-compose.yml -f docker-compose.dev.yml down -v
#docker logs docker_mongo_1 -f
