version: "3"
services: 
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
    command: node index.js
#  volumes:
#    - ./:/app
#    - /app/node_modules
#  command: npm run dev
#docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
#docker compose -f docker-compose.yml -f docker-compose.prod.yml down -v
#docker ps
#docker exec -it docker_node-app_1 bash

